name: Release version

on:
  push:
    branches:
      - main
      - "push-action/**"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run foonver
        id: foonver
        uses: foonly/foonver@v0.14.0
        with:
          command: "auto"
          changelog: "true"
          push: "true"
          commit_suffix: "[skip ci]"
          version_file: "module.json"

      - name: Create Release Zip
        if: steps.foonver.outputs.is_bumped == 'true'
        run: zip -r usr-victoria.zip * -x@.zipexclude

      - name: Create GitHub Release
        if: steps.foonver.outputs.is_bumped == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.foonver.outputs.version }}
          name: Release ${{ steps.foonver.outputs.version }}
          body: ${{ steps.foonver.outputs.release_notes }}
          files: |
            module.json
            usr-victoria.zip
